# .github/workflows/merge.yml
name: Merge NewStein into Main

on:
  push:
    branches:
      - NewStein # replace with your branch name

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Merge NewStein into main
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch origin main
          git checkout main
          git merge --no-commit --no-ff origin/NewStein || true # Try to merge, ignore exit code
          if [ $? -eq 0 ]; then
            git commit -m "Merge NewStein into main"
            git push origin main
          else
            echo "Merge conflict! Manual intervention required."
            exit 1
          fi
